### ISSUE TITLE
Long DKIM Keys (or other long TXT record) lead to syntax error in bind9

### ISSUE THREAD

**Issue by em0lar** [kirelagin/dns.nix#14]
Bind9 has a length limit for TXT records.

When creating e.g. a DKIM record with the following key: `MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0D9oTjw3GT1mQY7oOb9k7oEqxwFzpH3x0+5I3BzPiahiuhUdXgW5pt1KOddwVLzxsKkqTkTACyLRAaJVX4yKq06GeiIKYE8NU1Tt+N4/cUVjLqWQ8q80u8UkLdgrdIlwBb+p079OXogSnpg0N762bqyB1uEADhUNjRP6lQMYfBAzqVJNkUo4ABm+GsWlcPuhOBc0Sp6F5IhvBx/uyyzz46f/50kHOQgYWCblGwglrX9awEEBiMtWtGNBH7iO0DqL4AiJJC8PBvj2kS5sCdZRfCHRBGPczClmvCWf2JA6pL+PFqwtne35KGFIRHOluv3cn6YzQU3jhTaMMOWrgXHcFQIDAQAB`

the record is too long and leads to a syntax error in the zone.

This behavior is confirm to [RFC 1035](https://tools.ietf.org/html/rfc1035) Section 3.3:
> \<character-string> is treated as binary information, and can be up to 256 characters in length (including the length octet).

A fix is available over here: https://serverfault.com/questions/571720/publishing-long-domain-key-records-in-bind9

**Comment by kirelagin** [comment]
Uh-oh! I Thanks for reporting this, I had no idea.

I’ll gladly accept a PR that cuts TXT records into pieces of length 255. Or I might implement it myself hopefully some time next week.
